### ISSUE TITLE
Error in assignID: surface-property with name 'ceiling' does not exist.

### ISSUE THREAD

**Issue by kuxynator** [notnotmelon/factorissimo-2-notnotmelon#12] opened 2024-10-26 00:41 UTC
Failed to load mods: Error in assignID: surface-property with name 'ceiling' does not exist.

Source: nauvis-factory-floor (planet).

factorissimo-2-notnotmelon 1.5.1

**Comment by notnotmelon** [comment] 2024-10-26 00:51
Duplicate of #11

**Closed by notnotmelon** 2024-10-26 00:51 UTC
